version: '3.3'
services:
    mongodb:
        image: mongo:4.4.0-bionic
        volumes:
            - db-data:/usr/local/var/mongodb
        networks:
            - backend

    backend:
        build: ./server
        image: backtest-app-backend:latest
        ports:
            - '8080:8080'
        networks:
            - backend

    frontend:
        build: ./backtest-app
        image: backtest-app-frontend:latest
        ports:
            - '80:80'
        networks:
            - backend

networks:
    backend:

volumes:
    db-data:
